name: meshcat-shapes
channels:
    - conda-forge
dependencies:
    - pip >= 21.3.1
    - pip:
        - meshcat
        - meshcat-shapes
        - furo >= 2023.8.17
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - sphinx-mathjax-offline
        - sphinx-mdinclude
